### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by mmallejac** [vegardit/docker-openldap#3]
Wow, first issue here ! :-)

I've found this repo since I wasn't satisfied with [Bitnami](https://hub.docker.com/r/bitnami/openldap/), and [osixia](https://github.com/osixia/docker-openldap) is no longer maintained.

Except for time sync, I do not see any volume for data persistence: do you rely on backup / restore of `/var/lib/ldap/data.ldif` at restart or did I miss something ?

Also, I've designed our LDAP directory so that the same group is referenced within multiple OU's, wich seems to be in contradiction with your `init_module_unique.ldif` overlay config. To override this, should I simple mount `/opt/ldifs/` as a volume or is there another way ?
Finally, we use replication, so we need the `syncprov` overlay, so basically the same question.

Many thanks for this nice project,
Michel

**Comment by sebthom** [comment]
Regarding mounts, here is an extract from a compose file I am using to run the image:

```yaml
version: '3.8' 

secrets:
   secrets.sh:
     name: openldap_secrets.sh  # https://github.com/moby/moby/issues/35048#issuecomment-424372653
     file: ${SECRETS_FILE}

services:
  service:
    <<: *default-opts
    image: vegardit/openldap:latest
    secrets: [ secrets.sh ]
    environment:
      INIT_SH_FILE: '/run/secrets/secrets.sh'
      LDAP_INIT_ORG_DN: 'o=vegardit.com'
      LDAP_INIT_ORG_NAME: 'Vegard IT GmbH'
      LDAP_BACKUP_TIME: '02:00'
      LDAP_BACKUP_FILE: '/var/lib/ldap/data.ldif'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${STACK_DATA_ROOT}/init_org_entries.ldif:/opt/ldifs/init_org_entries.ldif:ro
      - ${STACK_DATA_ROOT}/init_org_tree.ldif:/opt/ldifs/init_org_tree.ldif:ro
      - ${STACK_DATA_ROOT}/service_db:/var/lib/ldap:rw
      - ${STACK_DATA_ROOT}/service_conf.d:/etc/ldap/slapd.d:rw
```

Here you find the commands that are executed on first container start:
https://github.com/vegardit/docker-openldap/blob/ec36a934deae25c9c71b078ee1d1300b8a6fc610/image/run.sh#L123-L148

You can overwrite the ldif files by mounting other versions directly on there path.
Regarding the syncpov overlay. You could SSH into the container after initial start and import the overlay manually or you owerwrite any of the existing files and replace/extend the content with what you need.

I hope that helps.
